export const week7 = {
    1: {
        home: 0,
        away: 0,
        homeName: "Raiders",
        awayName: "Chiefs",
        spread: 3,
        favorite: 0,
        favoriteName: "Chiefs",
        time: "8:25 PM",
        date: "Thursday, October 19",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    2: {
        home: 0,
        away: 0,
        homeName: "Vikings",
        awayName: "Ravens",
        spread: 5.5,
        favorite: 0,
        favoriteName: "Vikings",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    3: {
        home: 0,
        away: 0,
        homeName: "Packers",
        awayName: "Saints",
        spread: 4.5,
        favorite: 0,
        favoriteName: "Saints",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    4: {
        home: 0,
        away: 0,
        homeName: "Dolphins",
        awayName: "Jets",
        spread: 3,
        favorite: 0,
        favoriteName: "Dolphins",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    5: {
        home: 0,
        away: 0,
        homeName: "Bears",
        awayName: "Panthers",
        spread: 3,
        favorite: 0,
        favoriteName: "Panthers",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    6: {
        home: 0,
        away: 0,
        homeName: "Rams",
        awayName: "Cardinals",
        spread: 3.5,
        favorite: 0,
        favoriteName: "Rams",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    7: {
        home: 0,
        away: 0,
        homeName: "Bills",
        awayName: "Buccaneers",
        spread: 3.5,
        favorite: 0,
        favoriteName: "Bills",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    8: {
        home: 0,
        away: 0,
        homeName: "Colts",
        awayName: "Jaguars",
        spread: 3.5,
        favorite: 0,
        favoriteName: "Jaguars",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    9: {
        home: 0,
        away: 0,
        homeName: "Browns",
        awayName: "Titans",
        spread: 6,
        favorite: 0,
        favoriteName: "Titans",
        time: "1:00 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    10: {
        home: 0,
        away: 0,
        homeName: "49ers",
        awayName: "Cowboys",
        spread: 6,
        favorite: 0,
        favoriteName: "Cowboys",
        time: "4:05 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    11: {
        home: 0,
        away: 0,
        homeName: "Steelers",
        awayName: "Bengals",
        spread: 5.5,
        favorite: 0,
        favoriteName: "Steelers",
        time: "4:25 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    12: {
        home: 0,
        away: 0,
        homeName: "Giants",
        awayName: "Seahawks",
        spread: 5,
        favorite: 0,
        favoriteName: "Seahawks",
        time: "4:25 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    13: {
        home: 0,
        away: 0,
        homeName: "Chargers",
        awayName: "Broncos",
        spread: 1,
        favorite: 0,
        favoriteName: "Chargers",
        time: "4:25 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    14: {
        home: 0,
        away: 0,
        homeName: "Patriots",
        awayName: "Falcons",
        spread: 3.5,
        favorite: 0,
        favoriteName: "Patriots",
        time: "8:30 PM",
        date: "Sunday, October 22",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    15: {
        home: 0,
        away: 0,
        homeName: "Eagles",
        awayName: "Redskins",
        spread: 4.5,
        favorite: 0,
        favoriteName: "Eagles",
        time: "8:30 PM",
        date: "Monday, October 23",
        channel: "",
        winnerName: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    }
};