export const week6 = {
    1: {
        home: 0,
        away: 0,
        homeName: "Panthers",
        awayName: "Eagles",
        spread: 0,
        favorite: 0,
        favoriteName: "Eagles",
        time: "",
        date: "Thursday, October 12",
        channel: "",
        winner: 6,
        homeFinal: 23,
        awayFinal: 28
    },
    2: {
        home: 0,
        away: 0,
        homeName: "Ravens",
        awayName: "Bears",
        spread: 6.5,
        favorite: 0,
        favoriteName: "Ravens",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    3: {
        home: 0,
        away: 0,
        homeName: "Vikings",
        awayName: "Packers",
        spread: 3,
        favorite: 0,
        favoriteName: "Packers",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    4: {
        home: 0,
        away: 0,
        homeName: "Redskins",
        awayName: "49ers",
        spread: 10.5,
        favorite: 0,
        favoriteName: "Redskins",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    5: {
        home: 0,
        away: 0,
        homeName: "Saints",
        awayName: "Lions",
        spread: 4.5,
        favorite: 0,
        favoriteName: "Saints",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    6: {
        home: 0,
        away: 0,
        homeName: "Falcons",
        awayName: "Dolphins",
        spread: 12.5,
        favorite: 0,
        favoriteName: "Falcons",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    7: {
        home: 0,
        away: 0,
        homeName: "Texans",
        awayName: "Browns",
        spread: 9.5,
        favorite: 0,
        favoriteName: "Texans",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    8: {
        home: 0,
        away: 0,
        homeName: "Jets",
        awayName: "Patriots",
        spread: 9.5,
        favorite: 0,
        favoriteName: "Patriots",
        time: "1:00 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    9: {
        home: 0,
        away: 0,
        homeName: "Cardinals",
        awayName: "Buccaneers",
        spread: 1.5,
        favorite: 0,
        favoriteName: "Buccaneers",
        time: "4:05 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    10: {
        home: 0,
        away: 0,
        homeName: "Jaguars",
        awayName: "Rams",
        spread: 2.5,
        favorite: 0,
        favoriteName: "Jaguars",
        time: "4:05 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    11: {
        home: 0,
        away: 0,
        homeName: "Raiders",
        awayName: "Chargers",
        spread: 2,
        favorite: 0,
        favoriteName: "Raiders",
        time: "4:25 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    12: {
        home: 0,
        away: 0,
        homeName: "Chiefs",
        awayName: "Steelers",
        spread: 4.5,
        favorite: 0,
        favoriteName: "Chiefs",
        time: "4:25 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    13: {
        home: 0,
        away: 0,
        homeName: "Broncos",
        awayName: "Giants",
        spread: 12,
        favorite: 0,
        favoriteName: "Broncos",
        time: "8:30 PM",
        date: "Sunday, October 15",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    },
    14: {
        home: 0,
        away: 0,
        homeName: "Titans",
        awayName: "Colts",
        spread: '0 - EVEN MATCH',
        favorite: 0,
        favoriteName: "Titans",
        time: "8:30 PM",
        date: "Monday, October 16",
        channel: "",
        winner: 0,
        homeFinal: 0,
        awayFinal: 0
    }
};