export const week5 = {
    1: {
        home: 0,
        away: 0,
        homeName: "Buccaneers",
        awayName: "Patriots",
        spread: 'I DON\'T KNOW',
        favorite: 0,
        favoriteName: "Patriots",
        time: "",
        date: "Thursday, October 5",
        channel: "",
        winner: 3,
        winnerName: "Patriots",
        homeFinal: 14,
        awayFinal: 19
    },
    2: {
        home: 0,
        away: 0,
        homeName: "Colts",
        awayName: "49ers",
        spread: 1.5,
        favorite: 18,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Colts",
        favoriteName: "Colts",
        homeFinal: 26,
        awayFinal: 23
    },
    3: {
        home: 0,
        away: 0,
        homeName: "Browns",
        awayName: "Jets",
        spread: '0 - EVEN MATCH',
        favorite: 11,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Jets",
        favoriteName: "Browns",
        homeFinal: 14,
        awayFinal: 17
    },
    4: {
        home: 0,
        away: 0,
        homeName: "Steelers",
        awayName: "Jaguars",
        spread: 8,
        favorite: 12,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Jaguars",
        favoriteName: "Steelers",
        homeFinal: 9,
        awayFinal: 30
    },
    5: {
        home: 0,
        away: 0,
        homeName: "Giants",
        awayName: "Chargers",
        spread: 3,
        favorite: 6,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Chargers",
        favoriteName: "Giants",
        homeFinal: 22,
        awayFinal: 27
    },
    6: {
        home: 0,
        away: 0,
        homeName: "Bengals",
        awayName: "Bills",
        spread: 3,
        favorite: 10,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Bengals",
        favoriteName: "Bengals",
        homeFinal: 20,
        awayFinal: 16
    },
    7: {
        home: 0,
        away: 0,
        homeName: "Lions",
        awayName: "Panthers",
        spread: 2.5,
        favorite: 14,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Panthers",
        favoriteName: "Lions",
        homeFinal: 24,
        awayFinal: 27
    },
    8: {
        home: 0,
        away: 0,
        homeName: "Dolphins",
        awayName: "Titans",
        spread: 2.5,
        favorite: 20,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Dolphins",
        favoriteName: "Titans",
        homeFinal: 16,
        awayFinal: 10
    },
    9: {
        home: 0,
        away: 0,
        homeName: "Eagles",
        awayName: "Cardinals",
        spread: 6.5,
        favorite: 7,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Eagles",
        favoriteName: "Eagles",
        homeFinal: 34,
        awayFinal: 7
    },
    10: {
        home: 0,
        away: 0,
        homeName: "Ravens",
        awayName: "Raiders",
        spread: 3,
        favorite: 28,
        time: "4:05 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Ravens",
        favoriteName: "Raiders",
        homeFinal: 30,
        awayFinal: 17
    },
    11: {
        home: 0,
        away: 0,
        homeName: "Rams",
        awayName: "Seahawks",
        spread: 1.5,
        favorite: 30,
        time: "4:05 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Seahawks",
        favoriteName: "Rams",
        homeFinal: 10,
        awayFinal: 16
    },
    12: {
        home: 0,
        away: 0,
        homeName: "Cowboys",
        awayName: "Packers",
        spread: 2.5,
        favorite: 5,
        time: "4:25 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Packers",
        favoriteName: "Cowboys",
        homeFinal: 31,
        awayFinal: 35
    },
    13: {
        home: 0,
        away: 0,
        homeName: "Texans",
        awayName: "Chiefs",
        spread: 1,
        favorite: 26,
        time: "8:30 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null,
        winnerName: "Chiefs",
        favoriteName: "Chiefs",
        homeFinal: 34,
        awayFinal: 42
    },
    14: {
        home: 0,
        away: 0,
        homeName: "Bears",
        awayName: "Vikings",
        spread: 2.5,
        favorite: 16,
        time: "8:30 PM",
        date: "Monday, October 9",
        channel: "",
        winner: null,
        winnerName: "Vikings",
        favoriteName: "Vikings",
        homeFinal: 17,
        awayFinal: 20
    }
};