export const week5 = {
    1: {
        home: 0,
        away: 0,
        homeName: "Buccaneers",
        awayName: "Patriots",
        spread: 0,
        favorite: 0,
        time: "",
        date: "Thursday, October 5",
        channel: "",
        winner: 3,
        homeFinal: 14,
        awayFinal: 19
    },
    2: {
        home: 0,
        away: 0,
        homeName: "Colts",
        awayName: "49ers",
        spread: 1.5,
        favorite: 18,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    3: {
        home: 0,
        away: 0,
        homeName: "Browns",
        awayName: "Jets",
        spread: '0 - EVEN MATCH',
        favorite: 11,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    4: {
        home: 0,
        away: 0,
        homeName: "Steelers",
        awayName: "Jaguars",
        spread: 8,
        favorite: 12,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    5: {
        home: 0,
        away: 0,
        homeName: "Giants",
        awayName: "Chargers",
        spread: 3,
        favorite: 6,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    6: {
        home: 0,
        away: 0,
        homeName: "Bengals",
        awayName: "Bills",
        spread: 3,
        favorite: 10,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    7: {
        home: 0,
        away: 0,
        homeName: "Lions",
        awayName: "Panthers",
        spread: 2.5,
        favorite: 14,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    8: {
        home: 0,
        away: 0,
        homeName: "Dolphins",
        awayName: "Titans",
        spread: 2.5,
        favorite: 20,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    9: {
        home: 0,
        away: 0,
        homeName: "Eagles",
        awayName: "Cardinals",
        spread: 6.5,
        favorite: 7,
        time: "1:00 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    10: {
        home: 0,
        away: 0,
        homeName: "Ravens",
        awayName: "Raiders",
        spread: 3,
        favorite: 28,
        time: "4:05 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    11: {
        home: 0,
        away: 0,
        homeName: "Rams",
        awayName: "Seahawks",
        spread: 1.5,
        favorite: 30,
        time: "4:05 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    12: {
        home: 0,
        away: 0,
        homeName: "Cowboys",
        awayName: "Packers",
        spread: 2.5,
        favorite: 5,
        time: "4:25 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    13: {
        home: 0,
        away: 0,
        homeName: "Texans",
        awayName: "Chiefs",
        spread: 1,
        favorite: 26,
        time: "8:30 PM",
        date: "Sunday, October 8",
        channel: "",
        winner: null
    },
    14: {
        home: 0,
        away: 0,
        homeName: "Bears",
        awayName: "Vikings",
        spread: 2.5,
        favorite: 16,
        time: "8:30 PM",
        date: "Monday, October 9",
        channel: "",
        winner: null
    }
};